### PR TITLE
[RFC] Allow a discriminant to constrain a scalar type in a record

### PR DESCRIPTION
**Pull request by WRidder**
WIP. Would love to hear some initial thoughts on this matter.

https://github.com/WRidder/ada-spark-rfcs/blob/master/considered/rfc-allow-discriminants-to-constrain-scalar-type.rst

### CODE REVIEW

**Comment by yakobowski** [comment]
Rendered view: https://github.com/WRidder/ada-spark-rfcs/blob/master/considered/rfc-allow-discriminants-to-constrain-scalar-type.rst

**Comment by yakobowski** [comment]
Hi @WRidder . This is an interesting idea, and we will make sure to give you some feedback on it. However, since it is very preliminary at this stage, do you mind converting it into an issue? Thanks.

**Comment by WRidder** [comment]
Related issue: #72

**Comment by yakobowski** [comment]
Thanks for the issue. Closing this PR for the moment, we will reopen once we are at a more advanced stage.

**Pull request closed without merging**
